### ISSUE TITLE
Polarized Stone & Mending

### ISSUE THREAD

**Issue by FunkeyMonkey** [XzeroAir/Trinkets#34]
Running RL Craft modpack so not sure if it's this mod or something interfering but with polarized stone equipped and instant collect exp on, it's preventing mending from working on items. If i turn instant collect or magnetization off and run near/over orbs my bow mends up, soon as i turn on polar stone and it instant collects xp the bow stops repairing.

**Comment by XzeroAir** [comment]
Yeah, That's a Side effect of the Instant XP Collection, I'll Try and see if I can figure out a Solution so Mending still Functions as normal, But, I Can't really Guarantee anything because how MC handles Experience is really weird lol.

**Comment by FunkeyMonkey** [comment]
Ah i gotcha, hopefully it's an easy fix. Love the mod and having instant xp working would be the icing on the cake! :)

**Comment by XzeroAir** [comment]
@FunkeyMonkey I can finally say, This will be a feature in 0.31
https://www.curseforge.com/minecraft/mc-mods/trinkets-and-baubles/files/3379617
